version: 3.x

services:
  clashperk_bot:
    image: clashperk_bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    mem_limit: 2gb
    container_name: clashperk_bot
