version: "3.6"

services:
  clashperk_dev:
    image: clashperk_dev
    restart: always
    build:
      context: .
      dockerfile: .github/Dockerfile
    env_file:
      - .env.dev
    mem_limit: 3gb
    container_name: clashperk_dev
    ports:
      - "8070:8080"
    networks:
      - default_net

networks:
  default_net:
    external: true
    name: default_net