name: deploy-custom-bot

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy-custom-bot
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          curl --fail --location --request POST 'http://${{ secrets.AUTO_DEPLOYMENT_SERVICE_HOST }}/github-webhook' \
            --header 'x-api-key: ${{ secrets.AUTO_DEPLOYMENT_SERVICE_API_KEY }}'
