name: deploy-main-bot

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy-main-bot
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: curl --fail --location --request POST '${{ secrets.PORTAINER_WEBHOOK_URL }}'
