name: CD/Sentry

on:
  push:
  pull_request:

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: suvajit
  SENTRY_PROJECT: clashperk_bot

jobs:
  lint:
    name: Sentry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Init Submodule
        run: git submodule init && git submodule update --remote

      - name: NPM Install
        run: npm i

      - name: Run ESLint
        run: npm run test

      - name: Build
        run: npm run build

      - name: Release to Sentry
        run: npm run build:sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
