name: update-custom-bot-commands
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 5'
    - cron: '0 8 * * 1'
  push:
    tags:
      - '*'
    paths:
      - scripts/**

jobs:
  build:
    name: update-custom-bot-commands
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Init Submodule
        run: git submodule init && git submodule update --remote

      - name: NPM Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy -- --custom-bot
        env:
          CRYPTO_KEY: ${{ secrets.CRYPTO_KEY }}
          CRYPTO_IV: ${{ secrets.CRYPTO_IV }}
          SERVICE_API_KEY: ${{ secrets.SERVICE_API_KEY }}
          SERVICE_API_URL: ${{ secrets.SERVICE_API_URL }}
