name: update-main-bot-commands

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 5'
    - cron: '0 8 * * 1'
  push:
    branches:
      - main
    paths:
      - scripts/**

jobs:
  build:
    name: update-main-bot-commands
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Init Submodule
        run: git submodule init && git submodule update --remote

      - name: NPM Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy -- --gh-action
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
